name: 'Terraform Infrastructure Deployment'

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform.yml'
  workflow_dispatch:

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  TF_STATE_RESOURCE_GROUP_NAME: ${{ secrets.TF_STATE_RESOURCE_GROUP_NAME }}
  TF_STATE_STORAGE_ACCOUNT_NAME: ${{ secrets.TF_STATE_STORAGE_ACCOUNT_NAME }}
  TF_STATE_CONTAINER_NAME: ${{ secrets.TF_STATE_CONTAINER_NAME }}
  TF_STATE_KEY: "terraform.tfstate"

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Create terraform.tfvars
      run: |
        cat > terraform.tfvars << EOL
        resource_group_name = "tf-demo-rg"
        location           = "australiaeast"
        environment        = "dev"
        EOL

    - name: Verify Terraform Files
      run: |
        pwd
        ls -la
        echo "Content of terraform.tfvars:"
        cat terraform.tfvars

    - name: Terraform Init
      run: |
        terraform init \
          -backend-config="resource_group_name=$TF_STATE_RESOURCE_GROUP_NAME" \
          -backend-config="storage_account_name=$TF_STATE_STORAGE_ACCOUNT_NAME" \
          -backend-config="container_name=$TF_STATE_CONTAINER_NAME" \
          -backend-config="key=$TF_STATE_KEY"

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      if: github.event_name == 'pull_request'
      run: terraform plan -no-color
      continue-on-error: true

    - name: Force unlock state (if locked)
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform force-unlock -force "$(terraform workspace show 2>/dev/null)"
      continue-on-error: true

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        # Attempt to acquire lock and apply changes
        for i in {1..3}; do
          if terraform apply -auto-approve -var-file="terraform.tfvars"; then
            echo "Terraform apply succeeded"
            break
          else
            echo "Attempt $i failed. Waiting 30 seconds before retry..."
            sleep 30
            # Try to force unlock in case of lock
            terraform force-unlock -force "$(terraform workspace show 2>/dev/null)" || true
          fi
          if [ $i -eq 3 ]; then
            echo "All attempts failed"
            exit 1
          fi
        done
